### ISSUE TITLE
haywire_hello_world sometimes segfaults

### ISSUE THREAD

**Issue by HenkPoley** [haywire/haywire#101]
To CMakeLists.txt add: add_definitions(-fsanitize=address)

Run: 
```
rm -rf ./builds/unix/debug/*
./build.sh
./builds/unix/debug/haywire_hello_world
```

Request a couple of http://localhost:8000/ and eventually it will segfault.

(supposedly) due to a problem in route_compare_method.c: https://github.com/haywire/haywire/blob/master/src/haywire/route_compare_method.c#L58

https://twitter.com/pyr/status/698176813584027654

**Comment by HenkPoley** [comment]
Note the missing #include "hw_string.h" in route_compare_method.c that would have triggered a compile error.

**Comment by HenkPoley** [comment]
Hah, seems CMakeLists.txt is not the right place to add compiler options (for building on 'Mac').

That's why haywire_hello_world didn't output the typical ASAN output when an addressing error was found (!)

Anyways, the bug mentioned in route_compare_method.c is a legitimate bug.

**Comment by kellabyte** [comment]
Can you try this again using `make.sh` instead of `build.sh` please? We are deprecating `build.sh`.

**Comment by HenkPoley** [comment]
I'll close this issue. As the bugfix mentioned in the Twitter link is already applied in master right now.

It's probably up to somebody else to play with all the modern 'sanitizers' in GCC and Clang: http://clang.llvm.org/docs/index.html
