### ISSUE TITLE
How about haywire vs h2o or mongoose?

### ISSUE THREAD

**Issue by metalwood** [haywire/haywire#111]
h2o project
https://github.com/h2o/h2o

mongoose
https://github.com/cesanta/mongoose

I need a cross-platform high performance http server library(not http server daemon), h2o does not support windows very well, mongoose's performance is low(especially many clients or transform big file). Anyone make a benchmark comparison between haywire and nginx or h2o?

Thank you!

**Comment by kellabyte** [comment]
[This is an old not recent benchmark](https://gist.github.com/kellabyte/db163d97cff860ac4485) but at least I can show you something from the past.
