### ISSUE TITLE
Use uv_buf_init() in libuv alloc_cb()

### ISSUE THREAD

**Issue by kellabyte** [haywire/haywire#87]
It looks like we should be using `uv_buf_init()` in the libuv buffer allocation callback as follows:

```
void alloc_cb(uv_handle_t *handle, size_t size, uv_buf_t *buf) {
    int len;
    void *ptr = bufpool_acquire(handle->loop->data, &len);
    *buf = uv_buf_init(ptr, len);
}
```

http://docs.libuv.org/en/v1.x/misc.html#c.uv_buf_init
http://stackoverflow.com/questions/28511541/libuv-allocated-memory-buffers-re-use-techniques

**Comment by nmdguerreiro** [comment]
Fixed by #103
